import type { Metadata } from "next";
import Footer from "../components/Footer/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main
      >
        {children}
        <Footer />
    </main>
  );
}
